# Data Analysis

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Load CSV files
df_accepted = pd.read_csv("/Users/kavanamanvi/Desktop/creditRisk/accepted.csv")

/var/folders/b2/s6cq43q964gcjk0fp440gx_h0000gn/T/ipykernel_38460/1644585130.py:2: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  df_accepted = pd.read_csv("/Users/kavanamanvi/Desktop/creditRisk/accepted.csv")

In [4]:
df_rejected = pd.read_csv("/Users/kavanamanvi/Desktop/creditRisk/rejected.csv")

#### List of column names

In [11]:
df_accepted.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status', 'settlement_date',
       'settlement_amount', 'settlement_percentage', 'settlement_term'],
      dtype='object', length=151)

In [24]:
df_rejected = df_rejected.rename(columns={
    "Amount Requested": "LoanAmount",
    "Application Date": "Date",
    "Loan Title": "purpose",
    "Risk_Score": "riskScore",
    "Debt-To-Income Ratio": "debtToIncomeRatio",
    "Zip Code": "zipCode",
    "State": "state",
    "Employment Length": "employmentLength",
    "Policy Code": "policyCode"
})

In [43]:
df_rejected = df_rejected.drop(columns=["riskScore"])

In [44]:
df_rejected.columns

Index(['LoanAmount', 'Date', 'purpose', 'debtToIncomeRatio', 'zipCode',
       'state', 'employmentLength', 'policyCode', 'target'],
      dtype='object')

#### Common Columns

In [37]:
df_accepted = df_accepted.rename(columns={
    "loan_amnt": "LoanAmount",
    "issue_d": "Date",
    "purpose": "purpose",
    "dti": "debtToIncomeRatio",
    "zip_code": "zipCode",
    "addr_state": "state",
    "emp_length": "employmentLength",
    "policy_code": "policyCode"
})

In [60]:
#only keep common columns

rej_cols = [
    "LoanAmount",
    "Date",
    "purpose",
    "debtToIncomeRatio",
    "zipCode",
    "state",
    "employmentLength",
    "policyCode"
]

df_accepted = df_accepted[rej_cols]

In [61]:
# accepted = 0
df_accepted["target"] = 0

# rejected = 1
df_rejected["target"] = 1

In [64]:
df_accepted.head()

,LoanAmount,Date,purpose,debtToIncomeRatio,zipCode,state,employmentLength,policyCode,target
0,3600.0,Dec-2015,debt_consolidation,5.91,190xx,PA,10+ years,1.0,0
1,24700.0,Dec-2015,small_business,16.06,577xx,SD,10+ years,1.0,0
2,20000.0,Dec-2015,home_improvement,10.78,605xx,IL,10+ years,1.0,0
3,35000.0,Dec-2015,debt_consolidation,17.06,076xx,NJ,10+ years,1.0,0
4,10400.0,Dec-2015,major_purchase,25.37,174xx,PA,3 years,1.0,0

In [66]:
df_rejected.head()

,LoanAmount,Date,purpose,debtToIncomeRatio,zipCode,state,employmentLength,policyCode,target
0,1000.0,2007-05-26,Wedding Covered but No Honeymoon,10%,481xx,NM,4 years,0.0,1
1,1000.0,2007-05-26,Consolidating Debt,10%,010xx,MA,< 1 year,0.0,1
2,11000.0,2007-05-27,Want to consolidate my debt,10%,212xx,MD,1 year,0.0,1
3,6000.0,2007-05-27,waksman,38.64%,017xx,MA,< 1 year,0.0,1
4,1500.0,2007-05-27,mdrigo,9.43%,209xx,MD,< 1 year,0.0,1

### Merge Both datasets

In [54]:

df_merged = pd.concat(
    [df_accepted_aligned, df_rejected],
    ignore_index=True
)

# Shuffle rows
df = df_merged.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)